# Generated by Django 5.0.3 on 2024-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user_default.png', null=True, upload_to='profiles/'),
        ),
    ]
